### ISSUE TITLE
Dependency Required

### ISSUE THREAD

**Issue by Pelirrojo** [rubenCumbreno/dataviz_pec_final#1]
Hi,

I try to start the frontend and I receive this error:

````bash
(ENV) MacBook-Pro:frontend username$ python manage.py runserver localhost:1234
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/username/Workspace/Master/dataviz_pec_final/frontend/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/username/Workspace/Master/dataviz_pec_final/frontend/ENV/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/Users/username/Workspace/Master/dataviz_pec_final/frontend/ENV/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/username/Workspace/Master/dataviz_pec_final/frontend/ENV/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/username/Workspace/Master/dataviz_pec_final/frontend/ENV/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named datavizPecFinal.settings
````

**Could you help me please?**

**Comment by rubenCumbreno** [comment]
Hola ¿Puedes indicarme qué versión Django estás usando?

**Comment by Pelirrojo** [comment]
Claro, he estoy utilizando:
* virtual env: https://virtualenv.pypa.io/en/stable/userguide/#usage
* python 2.7 
* django==1.11.4 y django==2.0.7 (probé ambas).

Parece que echa en falta un fichero de settings: datavizPecFinal.settings

**Comment by rubenCumbreno** [comment]
Vale, el problema ha venido porque el git (o yo) no me ha subido dos archivos vacíos necesarios para django "__init__.py" sin los cuales no arranca la aplicación.

Ya están subidos y solucionado.
Vuelve a probar por favor, cualquier duda o cambio házmelo saber.
Gracias
